server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route  #id是唯一标识
          uri: lb://pms-service  #uri  是lb://服务名
          predicates:
            - Path=/pms/**   #Path：根据路径来跳转
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: index-route
          uri: lb://index-service
          predicates:
            - Host=gmall.com, index.gmall.com, www.gmall.com  #Host是根据域名来跳转，注，nginx要配置头信息;让访问携带头信息
          filters:
#            - AddResponseHeader=xxx,yyy
           # - Auth=/xxx,/yyy,/aaa,/bbb
#            - Auth=/            #只拦截gmall-index的模块下所有路径
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: order-route
          uri: lb://order-service
          predicates:
            - Host=order.gmall.com
          filters:
            - Auth=/
        - id: payment-route
          uri: lb://payment-service
          predicates:
            - Host=payment.gmall.com
          filters:
            - Auth=/
        - id: payment-route2
          uri: lb://payment-service
          predicates:
            - Path=/pay/**

auth:
  jwt:
    pubKeyPath: D:\AtGuiGuNeiNet\峰哥主讲2\rsa\rsa.pub
    cookieName: GMALL-TOKEN
    nickName: nickname