server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    sender:
      type: web
    discovery-client-enabled: false
    base-url: http://localhost:9411
  redis:
    host: 192.168.211.130
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    suffix: .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5
feign:
  sentinel:
    enabled: true

auth:
    jwt:
        pubKeyPath: D:\AtGuiGuNeiNet\峰哥主讲2\rsa\rsa.pub
        priKeyPath:  D:\AtGuiGuNeiNet\峰哥主讲2\rsa\rsa.pri
        secret: faf%fa@08fadf
        expire: 180
        #nickName作为cooikeName
        cookieName: GMALL-TOKEN
        #nickName作为cookieName
        nickName: unick


